<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nitsan_hellobar"
 *
 * Auto generated by Extension Builder 2016-04-28
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'NITSAN HelloBar - An API Plugin of HelloBar.com',
	'description' => 'An API Integration for HelloBar.com - One of the most popular site! Integrate hellobar panel(s) with simple configuration from TYPO3 Backend & Displaying it at global to your TYPO3 site!',
	'category' => 'plugin',
	'author' => 'Sanjay Chuahan',
	'author_email' => 'sanjay@nitsan.in',
	'author_company' => 'nitsan.in',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '3.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.0.0-8.9.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);
